apiVersion: v1
kind: Service
metadata:
  name: class-attendace-back
  namespace: production
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: class-attendace-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-attendace-back
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-attendace-back
  template:
    metadata:
      labels:
        app: class-attendace-back
    spec:
      containers:
        - name: class-attendace-back
          image: ghcr.io/sebastian-byui-projects/class-attendance-back:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: FRONTEND_URL
              value: "https://cs111-front.study-with-me.org"
          ports:
            - containerPort: 8000
              protocol: TCP
      imagePullSecrets:
        - name: github-registry-credentials
      restartPolicy: Always