apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: class-attendace-back-route
  namespace: production
spec:
  parentRefs:
    - name: shared-gateway
      group: gateway.networking.k8s.io
      namespace: envoy-gateway-system
  hostnames:
    - "cs111-back.study-with-me.org"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: class-attendace-back
          port: 8000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /